<!DOCTYPE html>
<html lang="es">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
	<link rel="stylesheet" href="css/bootstrap.min.css">
	<link rel="stylesheet" href="css/style.css">
	<link rel="stylesheet" href="css/videoSlide.css">
	<link rel="stylesheet" href="css/animate.css">
	<link rel="stylesheet" href="css/all.css">
	<title>CORSEC Consultores en responsabilidad social empresarial y calidad</title>
	<meta name="description" content="CORSEC Consultores en responsabilidad social empresarial y calidad" />
</head>
<body class="parallax">
	<div class="container-fluid fondoColor">
		<div class="row">
			<div class="col-12 m-0 p-0">