			<!-- ENCABEZADO -->
			<nav class="navbar navbar-expand-lg navbar-light fixed-top grisNav">
			  <a class="navbar-brand" href="index.php">
			  	<img src="img/logoNAV-01.svg" class="animated fadeInLeft" alt="Logo NAV">
			  </a>
			  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
			    <span class="navbar-toggler-icon"></span>
			  </button>

			  <div class="collapse navbar-collapse" id="navbarSupportedContent">
			    <ul class="navbar-nav mx-auto d-flex justify-content-center">
			      <li class="nav-item active p-1 eleSelect">
			        <a class="nav-link" href="index.php">INICIO <span class="sr-only">(current)</span></a>
			      </li>
			      <li class="nav-item p-1 eleSelect">
			        <a class="nav-link" href="nosotros.php">NOSOTROS</a>
			      </li>
			      <li class="nav-item p-1 eleSelect dropdown">
			        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
			          SERVICIOS
			        </a>
			        <div class="dropdown-menu animated fadeIn " aria-labelledby="navbarDropdown">
			          <a class="dropdown-item eleSelect p-2" href="optEmpre.php">Optimización Empresarial</a>
			          <a class="dropdown-item eleSelect p-2" href="respo.php">Responsabilidad Social Empresarial</a>
			          <a class="dropdown-item eleSelect p-2" href="#">Fortalecimiento Institucional</a>
			          <a class="dropdown-item eleSelect p-2" href="#">Formación y Capacitación</a>
			          <a class="dropdown-item eleSelect p-2" href="#">Tecnologías de la Información</a>
			        </div>
			      </li>
			      <li class="nav-item p-1 eleSelect">
			        <a class="nav-link" href="#">RESPONSABILIDAD CORPORATIVA</a>
			      </li>
			      <li class="nav-item p-1 eleSelect">
			        <a class="nav-link" href="#">ARTÍCULOS Y NOTICIAS</a>
			      </li>
			      <li class="nav-item p-1 eleSelect">
			        <a class="nav-link" href="#">CONTACTO</a>
			      </li>
			      <li class="nav-item">
			        <a class="nav-link" href="https://www.facebook.com/www.grupocorsec.com.mx/"><i class="fab fa-facebook-square icono animated infinite heartBeat"></i></a>
			      </li>
			      <li class="nav-item">
			        <a class="nav-link" href="https://twitter.com/grupocorsec"><i class="fab fa-twitter-square icono animated infinite heartBeat"></i></a>
			      </li>
			    </ul>
			    
			  </div>
			</nav>
			<!-- ENCABEZADO -->